### ISSUE TITLE
Sidebar expansion arrow randomly maxes out width

### ISSUE THREAD

**Issue by zorlaski** [redParrot17/Senior-Project-CAZM#11]
Happens on pageload, console shows no relevant errors or output
![Screenshot_2021-02-23 Document](https://user-images.githubusercontent.com/61090608/108808494-bf3c7a80-7574-11eb-81a9-fa977fc14ea0.png)

**Comment by redParrot17** [comment]
### Steps To Reproduce

1. Load the page.
2. Click the arrow to expand the sidebar.
3. Click the arrow to collapse the sidebar.
4. Quickly click the arrow to expand the sidebar as the collapse event is still running.

### Why This Is Happening

The event handler `toggleSideBar` within `static/js/side-bar.js` grabs a reference to the button via the parent object that triggered the event. When the problem occurs, that event handler is incorrectly determining which html element is the button and grabs the <div> element representing the table row/col element.

### Proposed Solution

1. Add a unique id to the button element.
```html
<div id="sidebar-button" class="ml-auto" onclick="toggleSideBar(event)"></div>
```

2. Grab a reference to the element via its id within the event handler.
```js
let btn = document.getElementById("sidebar-button");
```

**Comment by krausemj17** [comment]
finished/fixed this
