### ISSUE TITLE
Back button on student edit schedule page gives unauthorized error

### ISSUE THREAD

**Issue by AlecMuchnok** [redParrot17/Senior-Project-CAZM#43]
**Describe the bug**
When the back button is clicked on the student edit schedule page, the site goes to a page that says "Unauthorized"

**To Reproduce**
1. Log in
2. Click Edit Schedule button
3. Click Back button

**Expected behavior**
Site returns to student landing page

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version 89.0.4389.82 (Official Build) (64-bit) (cohort: Stable)

**Comment by redParrot17** [comment]
This will be resolved once pull request #45 gets merged.
A side effect is that it no longer works for the advisor page, but that will be resolved once the advisor editing page becomes distinct from the student side.
